export function getBoard(): any {
  const board = 
  {
    "map": [
      [
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": "Culture",
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Silk",
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": "Incense",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": "Hut",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": "Iron",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": "China",
          "civ": "China",
          "city": null,
          "defence": 0,
          "numberofArmies": 0,
          "numberofScouts": 1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": "Wheat",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Silk",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 2,
          "production": 1,
          "resource": null,
          "capciv": "China",
          "civ": "China",
          "city": null,
          "defence": 0,
          "numberofArmies": 2,
          "numberofScouts": 0,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": "Scientist"
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 5,
          "resource": null,
          "capciv": "China",
          "civ": "China",
          "city": "WalledCapital",
          "defence": 16,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 3,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 2,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": "University",
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Coin",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": "Wheat",
          "capciv": "China",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILECHINA.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE19.json",
          "hv": "Hut",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": "Village",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": "Hut",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": "Rome",
          "city": null,
          "defence": 0,
          "numberofArmies": 0,
          "numberofScouts": 1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": "Wheat",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Silk",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE1.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": "Village",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE15.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": "Iron",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": "Iron",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": "Hut",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": "Hut",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": "Culture",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": "Village",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Silk",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE2.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE18.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": "Wheat",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": "Village",
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": "Silk",
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": "Incense",
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "Rome",
          "civ": "Rome",
          "city": null,
          "defence": 0,
          "numberofArmies": 1,
          "numberofScouts": 0,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": "Rome",
          "city": null,
          "defence": 0,
          "numberofArmies": 1,
          "numberofScouts": 0,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": "Iron",
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 7,
          "resource": null,
          "capciv": "Rome",
          "civ": "Rome",
          "city": "Capital",
          "defence": 12,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 1,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ],
      [
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": "Silk",
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Grassland",
          "trade": 0,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Desert",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": null,
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILE6.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 1,
          "production": 0,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Mountain",
          "trade": 0,
          "production": 1,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Forest",
          "trade": 0,
          "production": 2,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": null,
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        },
        {
          "revealed": true,
          "terrain": "Water",
          "trade": 2,
          "production": 1,
          "resource": null,
          "capciv": "Rome",
          "civ": null,
          "city": null,
          "defence": 0,
          "numberofArmies": -1,
          "numberofScouts": -1,
          "tile": "RTILEROME.json",
          "hv": null,
          "building": "Shipyard",
          "wonder": null,
          "culture": 0,
          "greatperson": null,
          "greatpersontype": null
        }
      ]
    ],
    "game": {
      "roundno": 22,
      "phase": "Movement",
      "active": "China"
    },
    "units": {
      "units": [
        {
          "name": "Artillery",
          "num": 1
        },
        {
          "name": "Infantry",
          "num": 3
        },
        {
          "name": "Mounted",
          "num": 2
        },
        {
          "name": "Aircraft",
          "num": 8
        }
      ]
    },
    "killedunits": {
      "units": [
        {
          "name": "Artillery",
          "num": 4
        },
        {
          "name": "Infantry",
          "num": 5
        },
        {
          "name": "Mounted",
          "num": 6
        },
        {
          "name": "Aircraft",
          "num": 0
        }
      ],
      "list": [
        {
          "name": "Mounted",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Mounted",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Infantry",
          "strength": [
            1,
            2,
            3,
            4
          ]
        },
        {
          "name": "Artillery",
          "strength": [
            3,
            4,
            5,
            6
          ]
        },
        {
          "name": "Infantry",
          "strength": [
            3,
            4,
            5,
            6
          ]
        },
        {
          "name": "Infantry",
          "strength": [
            3,
            4,
            5,
            6
          ]
        },
        {
          "name": "Artillery",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Mounted",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Mounted",
          "strength": [
            1,
            2,
            3,
            4
          ]
        },
        {
          "name": "Artillery",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Infantry",
          "strength": [
            3,
            4,
            5,
            6
          ]
        },
        {
          "name": "Mounted",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Mounted",
          "strength": [
            3,
            4,
            5,
            6
          ]
        },
        {
          "name": "Infantry",
          "strength": [
            2,
            3,
            4,
            5
          ]
        },
        {
          "name": "Artillery",
          "strength": [
            3,
            4,
            5,
            6
          ]
        }
      ]
    },
    "resources": [
      {
        "resource": "Incense",
        "num": 2
      },
      {
        "resource": "Spy",
        "num": 0
      },
      {
        "resource": "Coin",
        "num": 0
      },
      {
        "resource": "Culture",
        "num": 0
      },
      {
        "resource": "Silk",
        "num": 2
      },
      {
        "resource": "Iron",
        "num": 2
      },
      {
        "resource": "Uranium",
        "num": 0
      },
      {
        "resource": "Wheat",
        "num": 0
      }
    ],
    "hutvillagesused": {
      "Hut": 2,
      "list": [
        {
          "hv": "Hut",
          "resource": "Spy"
        },
        {
          "hv": "Hut",
          "resource": "Incense"
        }
      ]
    },
    "you": {
      "tech": [
        {
          "tech": "Writing",
          "initial": true,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Agriculture",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Navy",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Metallurgy",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "HorsebackRiding",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "AnimalHusbandry",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Philosophy",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Pottery",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Currency",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Masonry",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "Navigation",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "CodeOfLaw",
          "initial": null,
          "level": 1,
          "coins": 0
        },
        {
          "tech": "PrintingPress",
          "initial": null,
          "level": 2,
          "coins": 0
        },
        {
          "tech": "Mathematics",
          "initial": null,
          "level": 2,
          "coins": 0
        }
      ],
      "gover": "Despotism",
      "civ": "China",
      "trade": 14,
      "commands": [
        {
          "command": "MOVE"
        },
        {
          "command": "ATTACK"
        }
      ],
      "citylimit": 1,
      "armieslimit": 4,
      "scoutslimit": 1,
      "tradeforprod": 3,
      "units": {
        "units": [
          {
            "name": "Artillery",
            "num": 5,
            "militarystrength": 1
          },
          {
            "name": "Infantry",
            "num": 4,
            "militarystrength": 0
          },
          {
            "name": "Mounted",
            "num": 4,
            "militarystrength": 0
          },
          {
            "name": "Aircraft",
            "num": 0,
            "militarystrength": 0
          }
        ],
        "list": [
          {
            "name": "Artillery",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Mounted",
            "strength": [
              1,
              2,
              3,
              4
            ]
          },
          {
            "name": "Artillery",
            "strength": [
              1,
              2,
              3,
              4
            ]
          },
          {
            "name": "Infantry",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Artillery",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Artillery",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Artillery",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Mounted",
            "strength": [
              1,
              2,
              3,
              4
            ]
          },
          {
            "name": "Infantry",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Infantry",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Mounted",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Infantry",
            "strength": [
              2,
              3,
              4,
              5
            ]
          },
          {
            "name": "Mounted",
            "strength": [
              2,
              3,
              4,
              5
            ]
          }
        ]
      },
      "resources": [
        {
          "resource": "Incense",
          "num": 0
        },
        {
          "resource": "Spy",
          "num": 0
        },
        {
          "resource": "Coin",
          "num": 0
        },
        {
          "resource": "Culture",
          "num": 1
        },
        {
          "resource": "Silk",
          "num": 0
        },
        {
          "resource": "Iron",
          "num": 0
        },
        {
          "resource": "Uranium",
          "num": 0
        },
        {
          "resource": "Wheat",
          "num": 0
        }
      ],
      "hutvillages": {
        "list": []
      },
      "wonders": [],
      "coins": 0,
      "combatbonus": 0,
      "cultureprogress": 4,
      "handsize": 3,
      "travelspeed": 3,
      "stacklimit": 3,
      "cultureresource": {
        "cardsno": 2,
        "personsno": 1,
        "personsused": [],
        "cards": [
          "BarbarianEncampment",
          "Disoriented"
        ],
        "persons": [
          "CharlesDarwin"
        ]
      },
      "suspended": null
    },
    "others": [
      {
        "tech": [
          {
            "tech": "CodeOfLaw",
            "initial": true,
            "level": 1,
            "coins": 1
          },
          {
            "tech": "Philosophy",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Metallurgy",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "AnimalHusbandry",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Masonry",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Pottery",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Navy",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Navigation",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Currency",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "HorsebackRiding",
            "initial": null,
            "level": 1,
            "coins": 0
          },
          {
            "tech": "Agriculture",
            "initial": null,
            "level": 1,
            "coins": 0
          }
        ],
        "gover": "Republic",
        "civ": "Rome",
        "trade": 5,
        "commands": [],
        "citylimit": 1,
        "armieslimit": 4,
        "scoutslimit": 1,
        "tradeforprod": 3,
        "units": {
          "units": [
            {
              "name": "Artillery",
              "num": 5,
              "militarystrength": 0
            },
            {
              "name": "Infantry",
              "num": 3,
              "militarystrength": 0
            },
            {
              "name": "Mounted",
              "num": 3,
              "militarystrength": 0
            },
            {
              "name": "Aircraft",
              "num": 0,
              "militarystrength": 0
            }
          ]
        },
        "resources": [
          {
            "resource": "Incense",
            "num": 0
          },
          {
            "resource": "Spy",
            "num": 0
          },
          {
            "resource": "Coin",
            "num": 0
          },
          {
            "resource": "Culture",
            "num": 2
          },
          {
            "resource": "Silk",
            "num": 0
          },
          {
            "resource": "Iron",
            "num": 0
          },
          {
            "resource": "Uranium",
            "num": 0
          },
          {
            "resource": "Wheat",
            "num": 2
          }
        ],
        "hutvillages": {
          "Village": 1
        },
        "wonders": [],
        "coins": 1,
        "combatbonus": 2,
        "cultureprogress": 3,
        "handsize": 3,
        "travelspeed": 3,
        "stacklimit": 3,
        "cultureresource": {
          "cardsno": 2,
          "personsno": 1,
          "personsused": [],
          "cards": null,
          "persons": null
        },
        "suspended": null
      }
    ],
    "wonders": [
      "TheGreatWall",
      "ChichenItza",
      "StatueofZeus",
      "ThePyramids"
    ],
    "battle": null,
    "buildings": [
      {
        "name": "Temple",
        "num": 5
      },
      {
        "name": "TradingPost",
        "num": 6
      },
      {
        "name": "Library",
        "num": 5
      },
      {
        "name": "Barracks",
        "num": 5
      },
      {
        "name": "Granary",
        "num": 6
      },
      {
        "name": "Shipyard",
        "num": 4
      },
      {
        "name": "Market",
        "num": 5
      },
      {
        "name": "Workshop",
        "num": 6
      },
      {
        "name": "Harbor",
        "num": 10
      }
    ],
    "cultureused": {
      "cardsno": 1,
      "personsno": 0,
      "personsused": [],
      "cards": [
        "Counterfeiters"
      ],
      "persons": []
    },
    "endofgame": null
  }

  return board;
}
