import React from 'react';

import Board from '../components/objects/board/Board'

const Test8: React.FC = () => {

    const board = 
    {
        "map": [
          [
            {
              "revealed": true,
              "terrain": "Mountain",
              "trade": 0,
              "production": 1,
              "resource": "Culture",
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Water",
              "trade": 1,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Forest",
              "trade": 0,
              "production": 2,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Water",
              "trade": 1,
              "production": 0,
              "resource": "Silk",
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": true,
              "terrain": "Mountain",
              "trade": 0,
              "production": 1,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Mountain",
              "trade": 0,
              "production": 1,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Forest",
              "trade": 0,
              "production": 2,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Forest",
              "trade": 0,
              "production": 2,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": true,
              "terrain": "Mountain",
              "trade": 0,
              "production": 1,
              "resource": "Iron",
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Desert",
              "trade": 1,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Grassland",
              "trade": 0,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Grassland",
              "trade": 0,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": true,
              "terrain": "Desert",
              "trade": 1,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Desert",
              "trade": 1,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Desert",
              "trade": 1,
              "production": 0,
              "resource": null,
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": true,
              "terrain": "Grassland",
              "trade": 0,
              "production": 0,
              "resource": "Wheat",
              "capciv": "China",
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILECHINA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE3.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": "Village",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE8.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILEINDIA.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": "Village",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE4.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE17.json",
              "hv": "Village",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ],
          [
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE16.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": "Hut",
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            },
            {
              "revealed": false,
              "terrain": null,
              "trade": -1,
              "production": -1,
              "resource": null,
              "capciv": null,
              "civ": null,
              "city": null,
              "defence": 0,
              "numberofArmies": -1,
              "numberofScouts": -1,
              "tile": "RTILE19.json",
              "hv": null,
              "building": null,
              "wonder": null,
              "culture": 0,
              "greatperson": null,
              "greatpersontype": null
            }
          ]
        ],
        "game": {
          "roundno": 0,
          "phase": "StartOfTurn",
          "active": "China"
        },
        "units": {
          "units": [
            {
              "name": "Artillery",
              "num": 14
            },
            {
              "name": "Infantry",
              "num": 14
            },
            {
              "name": "Mounted",
              "num": 14
            },
            {
              "name": "Aircraft",
              "num": 8
            }
          ]
        },
        "killedunits": {
          "units": [
            {
              "name": "Artillery",
              "num": 0
            },
            {
              "name": "Infantry",
              "num": 0
            },
            {
              "name": "Mounted",
              "num": 0
            },
            {
              "name": "Aircraft",
              "num": 0
            }
          ],
          "list": []
        },
        "resources": [
          {
            "resource": "Incense",
            "num": 1
          },
          {
            "resource": "Spy",
            "num": 0
          },
          {
            "resource": "Coin",
            "num": 0
          },
          {
            "resource": "Culture",
            "num": 0
          },
          {
            "resource": "Silk",
            "num": 1
          },
          {
            "resource": "Iron",
            "num": 1
          },
          {
            "resource": "Uranium",
            "num": 0
          },
          {
            "resource": "Wheat",
            "num": 1
          }
        ],
        "hutvillagesused": {
          "list": []
        },
        "you": {
          "tech": [
            {
              "tech": "Writing",
              "initial": true,
              "level": 1,
              "coins": 0
            }
          ],
          "gover": "Despotism",
          "civ": "China",
          "trade": 0,
          "commands": [
            {
              "command": "SETCAPITAL"
            }
          ],
          "citylimit": 2,
          "armieslimit": 6,
          "scoutslimit": 2,
          "tradeforprod": 3,
          "units": {
            "units": [
              {
                "name": "Artillery",
                "num": 1,
                "militarystrength": 0
              },
              {
                "name": "Infantry",
                "num": 1,
                "militarystrength": 0
              },
              {
                "name": "Mounted",
                "num": 1,
                "militarystrength": 0
              },
              {
                "name": "Aircraft",
                "num": 0,
                "militarystrength": 0
              }
            ],
            "list": [
              {
                "name": "Infantry",
                "strength": [
                  3,
                  4,
                  5,
                  6
                ]
              },
              {
                "name": "Artillery",
                "strength": [
                  2,
                  3,
                  4,
                  5
                ]
              },
              {
                "name": "Mounted",
                "strength": [
                  2,
                  3,
                  4,
                  5
                ]
              }
            ]
          },
          "resources": [
            {
              "resource": "Incense",
              "num": 0
            },
            {
              "resource": "Spy",
              "num": 0
            },
            {
              "resource": "Coin",
              "num": 0
            },
            {
              "resource": "Culture",
              "num": 0
            },
            {
              "resource": "Silk",
              "num": 0
            },
            {
              "resource": "Iron",
              "num": 0
            },
            {
              "resource": "Uranium",
              "num": 0
            },
            {
              "resource": "Wheat",
              "num": 0
            }
          ],
          "hutvillages": {
            "list": []
          },
          "wonders": [],
          "coins": 0,
          "combatbonus": 0,
          "cultureprogress": 0,
          "handsize": 2,
          "travelspeed": 2,
          "stacklimit": 2,
          "cultureresource": {
            "cardsno": 0,
            "personsno": 0,
            "personsused": [],
            "cards": [],
            "persons": []
          },
          "suspended": null
        },
        "others": [],
        "wonders": [
          "TheColossus",
          "TheGreatLighthouse",
          "StatueofZeus",
          "ChichenItza"
        ],
        "battle": null,
        "buildings": [
          {
            "name": "Temple",
            "num": 5
          },
          {
            "name": "TradingPost",
            "num": 6
          },
          {
            "name": "Library",
            "num": 6
          },
          {
            "name": "Barracks",
            "num": 5
          },
          {
            "name": "Granary",
            "num": 6
          },
          {
            "name": "Shipyard",
            "num": 5
          },
          {
            "name": "Market",
            "num": 5
          },
          {
            "name": "Workshop",
            "num": 6
          },
          {
            "name": "Harbor",
            "num": 10
          }
        ],
        "cultureused": {
          "cardsno": 0,
          "personsno": 0,
          "personsused": [],
          "cards": [],
          "persons": []
        },
        "endofgame": null
      };
      
    

    return (
        <div >
            <Board data={board} />
        </div>
    );
}

export default Test8;
